force_th_x: 
    zero: -11
    max: 18
    min: -18

force_th_y: 
    zero: -8
    max: 7
    min: -7

force_th_z: 
    zero: -85
    max: 1000
    min: 1000

vel_th_x: 
    max: 8
    min: 8
 
vel_th_y: 
    max: 8
    min: 8

continuity_x: 20

continuity_y: 18


      
        
        
        