force_th_x: 
    zero: 1.5
    max: 2.4
    min: -2.4

force_th_y: 
    zero: 0.8
    max: 1.8
    min: -1.8

force_th_z: 
    zero: -3.2
    max: 1000
    min: 1000

vel_th_x: 
    max: 2
    min: 2
 
vel_th_y: 
    max: 2
    min: 2

continuity_x: 20

continuity_y: 18


      
        
        
        